initial_joint_positions:
  lss_arm:
    lss_arm_joint_1: 0.0
    lss_arm_joint_2: 1.7
    lss_arm_joint_3: -0.7
    lss_arm_joint_4: -1.7
    lss_arm_joint_5: 0.0
  gripper_5dof:
    lss_arm_joint_6: 0.0